# see: https://docs.docker.com/compose/compose-file/

services:
  server:
    build:
      context: ../..
      dockerfile: docker/ssg/Dockerfile
    ports:
      - 5555:5555
    restart: unless-stopped
#     depends_on:
#       db:
#         condition: service_healthy

#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5

# volumes:
#   db-data:

# secrets:
#   db-password:
#     file: db/password.txt
